services:
    app:
        build: ./
        volumes:
            - ./:/app
        ports:
            - 3000:3000
        entrypoint: /bin/sh
        command:
            - -c
            - |
                npm install
                /usr/bin/xvfb-run -a npm run dev
    minio:
        image: minio/minio:latest
        ports:
            - 9000:9000 # S3-compatible API
            - 9001:9001 # Web Console
        environment:
            - MINIO_ROOT_USER=minioadmin
            - MINIO_ROOT_PASSWORD=minioadmin
        command: server --console-address ":9001" /data
        healthcheck:
            test:
                ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
            interval: 1s
            timeout: 20s
            retries: 3
