services:
    app:
        build: ./
        volumes:
            - ./src:/app/src
            - ./.cache:/app/.cache
            - ./localdata:/app/localdata
        ports:
            - 3000:3000
        entrypoint: /bin/sh
        command:
            - -c
            - |
                npm install
                /usr/bin/xvfb-run -a npm run dev
        environment:
            - CHIITILER_CACHE_METHOD=s3
            - CHIITILER_S3CACHE_BUCKET=chiitiler
            - CHIITILER_S3_REGION=ap-northeast-1
            - CHIITILER_S3_ENDPOINT=http://minio:9000
            - CHIITILER_S3_FORCE_PATH_STYLE=true
            - CHIITILER_PROCESSES=0
            - CHIITILER_STREAM_MODE=true
            - AWS_ACCESS_KEY_ID=minioadmin
            - AWS_SECRET_ACCESS_KEY=minioadmin
            - STORAGE_EMULATOR_HOST=http://fake-gcs-server:4443
            - CHIITILER_GCS_BUCKET=tiles
    minio:
        image: minio/minio:latest
        ports:
            - 9000:9000 # S3-compatible API
            - 9001:9001 # Web Console
        environment:
            - MINIO_ROOT_USER=minioadmin
            - MINIO_ROOT_PASSWORD=minioadmin
        command: server --console-address ":9001" /data
        healthcheck:
            test:
                ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
            interval: 1s
            timeout: 20s
            retries: 3
    createbuckets:
        image: minio/mc:RELEASE.2022-12-24T15-21-38Z
        depends_on:
            - minio
        entrypoint: >
            /bin/sh -c "
            mc alias set myminio http://minio:9000 minioadmin minioadmin;
            mc mb myminio/chiitiler;
            mc mb myminio/tiles;
            mc cp initdata/tiles/* myminio/tiles --recursive;
            "
        volumes:
            - ./localdata:/initdata
    fake-gcs-server:
        image: fsouza/fake-gcs-server:latest
        ports:
            - "4443:4443"
        volumes:
            - ./localdata:/data/tiles
        command: -scheme http
