name: Build and Deploy
on:
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Login GitHub Packages
              uses: docker/login-action@v1.13.0
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Docker のビルドと push
              uses: docker/build-push-action@v2.9.0
              with:
                  context: .
                  push: true
                  tags: ghcr.io/kanahiro/chiitiler:${{ github.event.release.tag_name }}, ghcr.io/kanahiro/chiitiler:latest
