name: test:integration

on:
    pull_request:
        branches:
            - main
        paths:
            - 'app/**'
    workflow_dispatch:

jobs:
    aws-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20'
                  cache: npm
                  cache-dependency-path: package-lock.json
            - name: start server
              run: docker compose up -d
            - name: run test
              run: |
                  npm ci
                  npm test:integration
