name: test:integration

on:
    pull_request:
        branches:
            - main
        paths:
            - 'src/**'
            - 'tests/**'
            - '.github/workflows/test:integration.yml'
    workflow_dispatch:

jobs:
    integrationtest:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20'
            - name: start server
              run: docker compose up -d
            - name: run test
              run: |
                  npm install
                  npm run test:integration
