name: TestApp

on:
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    unittest:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20'
                  cache: npm
                  cache-dependency-path: package-lock.json
            - name: Build App
              run: |
                  npm ci
                  npm test
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v4.0.1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: ./coverage/coverage-final.json
